### ISSUE TITLE
change self.*

### ISSUE THREAD

**Issue by bettet01** [bettet01/dnd_Char_creator#12]
need implementations to change each individual stat on a character manually. just a simple change feature with a add/remove input and then the change should suffice. no need to go crazy just simple +=  and -= shoud do it.

**Comment by bettet01** [comment]
this is probably quite a few methods. i didn't want to make an issues for each one.

**Comment by eehresmann94** [comment]
I think I have a good template for how I would like to add this enhancement but my main issue is getting my new stat(increased or decreased depending on the function being used) to replace the old stat from the character. 

More research is needed on how to best do this. 

I  think this enumerate built in may help. 

http://book.pythontips.com/en/latest/enumerate.html
