### ISSUE TITLE
Armor Class Calculator 

### ISSUE THREAD

**Issue by eehresmann94** [bettet01/dnd_Char_creator#6]
Calculate the Armor Class of a character.  This will be useful for the battle tracker later later down the road. 

Based upon some quick google research it would appear that in dnd 5e your inventory will be a critical part of tracking your AC since your shield and armor will affect your overall number.

**Things we will need to calculate the AC** 
1. Armor/ shields(does the player have it and what type is it(light, medium, or heavy?) 
2. Is the character proficient in the type of armor/ shield they would like to use and if they are not what   are the drawbacks?
3) Does their class offer them any extra boost to their AC? 
4) Are there any spells/ buffs in play that will affect the character?

feel free to add to this list if you find any other variables.   

Sources: 
D&D Players handbook 5e: Chapter 1 pg 14 and Chapter 5 pgs 144 and 145)
https://merricb.com/2014/09/13/armour-class-in-dungeons-dragons-5e/

**Comment by bettet01** [comment]
Made a simpler version for now that you just calculate and input the AC. will fix in mark 2.
