### ISSUE TITLE
character inventory system part 1

### ISSUE THREAD

**Issue by eehresmann94** [bettet01/dnd_Char_creator#9]
create a method/csv sheety to track all of the inventory that a character currently holds and reference this sheet during the battle if need be.   

A rough outline of how to proceed 

1) create an char_inventory.csv 
2) create columns that hold all of the types of items you could possibly have(armor, weapons,money,food(if applicable)) 
     a) if possible try to find a way to label each type of item for reference later( light armor vs heavy, simple weapons vs  combat weapon) 
     b) if possible try to link the given chars proficiency with each weapon. 
2) import the char name from the char_master file.csv to ensure continuity and reduce double entries. 
3) create distinctions between what item a character currently has equipped and other auxiliary items they may have(this could be done by creating main weapon column vs aux 1 weapon column, aux 2, etc) the function should be able to switch the values of the columns, Aux 1 becomes the main weapon and vise versa.

**Comment by bettet01** [comment]
can we implement this with lists instead of another csv file? i'm thinking a few lists involving armor weapons and general inventory and then push those to the character list instead.
